# Welcome to Jekyll!

# Website settings
title: oscarbarrios.tech
description: > # this means to ignore newlines until "keywords:"
  Hello everyone! I'm Oscar Barrios, and I'm thrilled to introduce you to oscarbarrios.tech, my new space for exploring the intersection of Testing and DevOps. As a QE Architect and a big fan of Agile methodologies and DevOps culture , I've spent years embracing new technologies and building robust software architectures across companies like SUSE , King Activision Blizzard , and Telefónica Digital. My experience in scaling testing, developing CI/CD pipelines , and driving quality standards  has shown me the power of bringing automation, tools, and processes together. From building AI-powered PR analysis tools and implementing CI-integrated synthetic monitoring , to mentoring the next generation of engineers , I'm passionate about sharing ideas related to DevOps, Automation, and QA. At oscarbarrios.tech, I plan to share insights, articles, and code on topics like Infrastructure as Code (IaC), Continuous Integration/Continuous Deployment (CI/CD), smart test selection, and the latest tools in the TestOps landscape—including those from my current tech stack like Terraform, Prometheus, Grafana, Python, Go, Selenium, and Ollama. Join me as we explore how to achieve Quality on Autopilot!
keywords: blog, oscar, barrios, qa, automation, testing, devops, development, selenium
#baseurl:  /Jalpc # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
# url: https://srbarrios.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Oscar Barrios Torrero  # Be used at blog posts' author.
  first_name: Oscar  # Be used at index page about me section.
  last_name: Barrios  # Be used at index page about me section.
  avatar: /static/assets/img/landing/oscar-barrios.png  # upload your avatar at directory and edit it.
  github_username: srbarrios  # Leave blank if you don't have now
  linkedin_id: oscarbarrios # Leave blank if you don't have now
  gitlab_username: oscar.barrios  # Leave blank if you don't have now
  #twitter_username:   # Leave blank if you don't have now
  email: oscarbarrios@gmail.com  # Leave blank if you don't have now
  cv: /static/assets/cv.pdf  # An online CV can be printed as PDF, leave blank if you don't have now
  matrix: srbarrios
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fa-linux
    - name: icon-ruby
  skill_icon2:
    - name: icon-csharp
    - name: icon-java
  desc: >
    Software Engineer skilled in Quality Process and Automation, with expertise as a Backend Developer.
    <br>Big fan of Agile methodologies & DevOps culture

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: oubiti

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: G-YGDFX8WY5R

# analytics
## Google Tag Manager
gtm:
  id: G-YGDFX8WY5R

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

